services:
  - type: web
    name: microservico-nfe
    env: php
    plan: free
    buildCommand: 'composer install --no-interaction --prefer-dist --optimize-autoloader'
    startCommand: 'php artisan serve --host 0.0.0.0 --port 10000'
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: # coloque aqui a chave gerada pelo comando php artisan key:generate --show
      # Adicione outras variáveis do .env conforme necessário
